name: project
description: "Education app for students to practice questions based on their syllabus"
publish_to: 'none'
version: 2.1.2+11
environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.1.0
  cloud_firestore: ^5.6.0
  confetti: ^0.8.0
  file_picker: ^8.1.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_vertexai: ^1.0.4
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_math_fork: ^0.7.3
  flutter_speed_dial: ^7.0.0
  google_sign_in: ^6.2.2
  http: ^1.2.2
  intl: ^0.20.2
  provider: ^6.1.2
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_launcher_icons:
  image_path: "lib/assets/icon.png"
  android: true
  adaptive_icon_background: "assets/background_icon.png"
  adaptive_icon_foreground: "assets/foreground_icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
